version: "3.9"
services:
  server:
    working_dir: /app
    image: node:20
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./apps/server:/app
    ports:
      - "3000:3000"
    environment:
      - AI_ENGINE_URL=http://ai_engine:7001
      - DECISION_ENGINE_URL=http://decision_engine:7002
      - LLM2_URL=http://llm2:7003

  ai_engine:
    working_dir: /app
    image: python:3.11-slim
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 7001"
    volumes:
      - ./py/ai_engine:/app
    ports:
      - "7001:7001"

  decision_engine:
    working_dir: /app
    image: python:3.11-slim
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 7002"
    volumes:
      - ./py/decision_engine:/app
    ports:
      - "7002:7002"

  llm2:
    working_dir: /app
    image: python:3.11-slim
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 7003"
    volumes:
      - ./py/llm2:/app
    ports:
      - "7003:7003"
